name = "expense-tracker-backend"
main = "src/app.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# Dev server port
[dev]
port = 8787

# D1 Database binding — local dev mein SQLite use hoga
[[d1_databases]]
binding = "expense_tracker_db"
database_name = "expense_tracker"
database_id = "local"
